import type { Metadata } from "next";
import { site } from "@/lib/site";
import "./globals.css";

const title = "RENTAL819 — 日本電單車自駕遊";
const description =
  "頭盔王 × Rental819：香港騎士的日本電單車租賃及自駕遊團，橫跨全日本 99 間分店。";

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: title,
    template: "%s — RENTAL819",
  },
  description,
  icons: {
    icon: "/icon.png",
    apple: "/icon.png",
  },
  openGraph: {
    type: "website",
    siteName: "RENTAL819 HK",
    title,
    description,
    url: site.url,
    locale: "zh_HK",
    alternateLocale: ["en"],
    // og-image is generated by app/opengraph-image.tsx (1200×630)
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
  },
};

/**
 * Passthrough root layout — the real <html>/<body> live in app/[locale]/layout.tsx
 * so the `lang` attribute is correct per locale (Next.js i18n pattern).
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return children;
}
